# input("What's your name?: ")

# myName = input("What's you name?: ")
# myAge = input("How old are you? :")
# print("Gee, that's REALLY OLD")
# replit = input("Do you like Replit?")
# print("OF COURSE YOU DO!")
# print()
# print("So, you are")
# print(myName)
# print("and are the ripe old age of")
# print(myAge)
# print("and clearly think that Replit is")
# print(replit)
# myvariable = input("WHO GOES THERE? ")
# print(myvariable)
# mygrandma = input("How's your Grandma doing? 😘 ")
# print(mygrandma)
# myLunch = input("What are you having for lunch? ")
# print("Hmm, it sounds like you really should just order")
# print(myLunch)
# print("as soon as possible!")
# print("Definitely not a Phishing Scam")
# print()
# myName = input("What is your name?")
# print("Thanks for logging in")
# print(myName)
# cardNumber = input("What is your credit card number?")
# print("Thanks, I definitely wont put")
# print(cardNumber)
# print("into Amazon and order anything weird")
# print()
# print("Promise")
# maidenName = input("What is your Mother's maiden name? ")
# print()
# print("That's cool, I just wanted to know that")
# print(maidenName)
# print("was your Mum's maiden name. Not because the bank requested it or anything, honest.")
name = input("What is your name?")
favfood = input("What is your favourite food?")
favmusic = input("What is your favourite music?")
address = input("Where do you live?")
print()
print("so your name is")
print(name)
print("Your favourite food is")
print(favfood)
print("Your favourite music is")
print(favmusic)
print("and you lived at")
print(address)
print("Im glad I get you to know and I like your music named " +favmusic)
